<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LIM-7CBMXY2" name="SaceDemoTest" tests="2" failures="1" timestamp="7 Sep 2021 02:58:22 GMT" time="30.902" errors="0">
  <testcase name="open" time="22.409" classname="suite2.SauceDemoTests"/>
  <testcase name="login" time="3.435" classname="suite2.SauceDemoTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at suite2.SauceDemoTests.login(SauceDemoTests.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- SaceDemoTest -->
